
baseURL = "https://fractal-programming.github.io/blog/"
locale = 'en-us'
title = "Fractal Programming"
theme = "ananke"

[params]
site_logo = "images/logo.png"
body_classes = "avenir"
text_color = "near-white"
description = "Code reflecting natural patterns 🌳"
images = ["/blog/images/trees-main.webp"]
author = "Naegolus"
math = true
plantuml_server = "https://naegolus.us.to:8097"

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["$$", "$$"]]
    inline = [["$", "$"]]

