
baseURL = "https://fractal-programming.github.io/blog/"
locale = 'en-us'
title = "Fractal Programming"
#theme = "beautifulhugo"
theme = "ananke"

[params]
site_logo = "images/logo.png"
body_classes = "avenir"
text_color = "near-white"
description = "Code reflecting natural patterns 🌳"

