
baseURL = "https://fractal-programming.github.io/blog/"
locale = 'en-us'
title = "Fractal Programming"
#theme = "beautifulhugo"
theme = "ananke"

[params]
site_logo = "images/logo.png"
featured_image = "images/trees-main.jpeg"
#background_color_class = "#ff00ff"
